### ISSUE TITLE
Template comment error

### ISSUE THREAD

**Issue by Danieleeee** [zabel-xyz/plsql-language#10]
Hi,
in this case the extension recognizes mistakenly the procedure like a comment:
[img] http://i.imgur.com/rvAkjGB.jpg [/img]

`portale_utilita_rx.remove_namespace(xmltype(nmi_msg)`
if I delete 'm' it works.

**Comment by Danieleeee** [comment]
Proble is with "Rem" sting

**Comment by zabel-xyz** [comment]
Fix in version 1.0.0

**Comment by Danieleeee** [comment]
still in 1.0.0
