### ISSUE TITLE
Symbols: Package name Error

### ISSUE THREAD

**Issue by Danieleeee** [zabel-xyz/plsql-language#11]
Hi, if I put the scheme in the package name declaretion the symbols of the package dont works:

this case work:
[img] http://i.imgur.com/iE7uiqB.jpg [/img]

With SIU_INT. dont work:
[img] http://i.imgur.com/ONPnigB.jpg [/img]

**Comment by zabel-xyz** [comment]
Fix  in version 1.0.0
