### ISSUE TITLE
Generate documentation from comments

### ISSUE THREAD

**Issue by Danieleeee** [zabel-xyz/plsql-language#17]
Hi, congratulations for the automatic generation of documentation.
It works very well.
Which extension or tool do you suggest to genete html and/or pdf documentation from JDOC-like comments?

I also have a request, it's possbile to have the definition of the types in doc/comments?
![1](https://cloud.githubusercontent.com/assets/22749175/26279682/9874349c-3dba-11e7-96f3-66c1263eff3c.png)

**Comment by zabel-xyz** [comment]
I can't suggest any tools. (I don't use any).
Ok, for the request, I add the label "improvement" ...

**Comment by zabel-xyz** [comment]
Fix in version 1.1.1
