### ISSUE TITLE
file extension icons

### ISSUE THREAD

**Issue by Danieleeee** [zabel-xyz/plsql-language#18]
Hi,
can you look to this post:
Support for PCK file #964

It's true that change icon depends on your extensions?

**Comment by zabel-xyz** [comment]
Could you give me the address url ? What's the problem ?

**Comment by Danieleeee** [comment]
Yes, sorry.
[Support for PCK file #964](https://github.com/vscode-icons/vscode-icons/issues/964#issuecomment-304659149)

**Comment by zabel-xyz** [comment]
Currently the extension .pck is not supported. I'll add it.
The icon is the responsability of icon-extension (here vscode-icons). But I see you have discussed about it...
