### ISSUE TITLE
Unrecognized Symbols

### ISSUE THREAD

**Issue by Danieleeee** [zabel-xyz/plsql-language#19]
Hi, I have problems with symbols.
Symbols don't recognize constant variable:
![schermata 2017-06-13 alle 23 36 53](https://user-images.githubusercontent.com/22749175/27105830-499ef412-5091-11e7-8b82-0ba82c0f0ca2.png)
Why _**package CONSTANT**_ ? why have the same symbol of **_package body_**?
And where are **_kRevision#_**, **_kRevisionDate_**,... constants?

**Comment by Danieleeee** [comment]
Global variable are not recognized (ESITO_POSITIVO, ESITO_NEGATIVO, character_encoding_sii):
![schermata 2017-06-14 alle 00 00 50](https://user-images.githubusercontent.com/22749175/27106700-d5bcf536-5094-11e7-8ce7-5c3f00f86c2b.png)

**Comment by Danieleeee** [comment]
Type variable are not recognized (v_TaballegatoRep):
![schermata 2017-06-14 alle 00 07 35](https://user-images.githubusercontent.com/22749175/27106881-99bd949a-5095-11e7-9785-2c7dceba9799.png)

**Comment by Danieleeee** [comment]
I think that you have to update getSymbolKind() method.
Thanks.

**Comment by zabel-xyz** [comment]
Currently symbole list is limited (navigation too).
Only package, package body and methods (functions or procedures) are listed. into symbol list.
I'll improve this in the future (I have started with navigation see issue 8)

**Comment by Danieleeee** [comment]
Did you see [symbolkind](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namesymbolkindaspan-classcodeitem-id570symbolkindspan) in vscode documentation?

**Comment by zabel-xyz** [comment]
Of course, I use some of them !
SymbolKind must be associated with some regexp to parse the code and create the list.
(If you want you can make a PR to complete this list...)

**Comment by Danieleeee** [comment]
I download your extension and press f5 to debug, but have this error:
![schermata 2017-06-14 alle 22 37 56](https://user-images.githubusercontent.com/22749175/27153568-4363b648-5152-11e7-8d7a-1f4694c17086.png)

**Comment by Danieleeee** [comment]
PR here: [reference](https://github.com/zabel-xyz/plsql-language/compare/master...Danieleeee:patch-3)

**Comment by Danieleeee** [comment]
up

**Comment by Danieleeee** [comment]
Can you put Constants Symbol #25 in the main project?
It work well.

**Comment by zabel-xyz** [comment]
I refactor parser in Version 1.2.0, in order to consider global variables, constants, types in navigation and list of symbols.

**Comment by fernandoTorresan** [comment]
@Danieleeee Tell me what is the extension do you use, to show in the left bar with name "code outline", please?

**Comment by zabel-xyz** [comment]
The extension [here](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline)

**Comment by Danieleeee** [comment]
Hi zabel, I have still the same problem with constants visualization in version 1.2.2
Thanks.

**Comment by zabel-xyz** [comment]
In version 1.2.2, all symbols in the package specification must be recognized, but there is still a problem with the package body (see # 37)
I'm already working on this issue ...
