### ISSUE TITLE
go to symbol

### ISSUE THREAD

**Issue by callamaris** [zabel-xyz/plsql-language#2]
Hi,

i have an issue with the go to symbol function.

The symbol list contains additional entries, if the text "PROCEDURE my_procedure_name" occures in code comments.

Is it possible to ignore code comments when generating the symbol list?

**Comment by callamaris** [comment]
Seems to be only an issue, when using single line comments starting with --

**Comment by zabel-xyz** [comment]
I fixed "Ignoring names of methods in comments" in version 0.0.7.
But it's only for block comments, not for single line comments.
So I'll add this...

**Comment by zabel-xyz** [comment]
Fixed in version 0.0.8
