### ISSUE TITLE
Please add support for ".pls" extension

### ISSUE THREAD

**Issue by marziopulcini** [zabel-xyz/plsql-language#27]
Can you please add support for .pls file format (which is the default extension when Oracle SQLDeveloper tool exports file. I've done locally by myself by adding it to package.json

				"extensions": [
					".sql",
					".ddl",
					".dml",
					".pkb",
					".pkh",
					".pks",
					".pck",
					".pls"
					],

and to 

    <array>
        <string>sql</string>
        <string>ddl</string>
        <string>dml</string>
        <string>pks</string>
        <string>pkb</string>
        <string>pck</string>
	<string>pls</string>
    </array>

But it would be much better to have it supported in the standard.
Thanks a lot!

**Comment by zabel-xyz** [comment]
Fix in version 1.1.0
