### ISSUE TITLE
Support for multiple extensions

### ISSUE THREAD

**Issue by Ovrful** [zabel-xyz/plsql-language#28]
It would be very usefull if I could specifiy multiple random package specification/body extensions in plsql.tmLanguage file.
I have to deal with multiple different extensions for oracle packages like .sps, .spb, .epb... so feature like this would come real handy, so I dont have to modify source code whenever I come across new package extension :)

Thanks.

**Comment by zabel-xyz** [comment]
I don't understand exactly what you want...

But in **plsql.tmLanguage** file and **package.json**, I listed only a few list of possible extension (most common)
You can define others in vscode settings like this
`"files.associations": {"*.ebp": "plsql"}`

For navigation between files, list of extension is hard coded. I'll improve this....

**Comment by zhudock** [comment]
Would it be possible to expand the default list of file extensions to match those used by [langauge-oracle](https://github.com/OraOpenSource/language-oracle/blob/master/grammars/pl%20sql%20(oracle).cson) Atom package?

Adding them manually is easy enough, but they seemed to have a rather comprehensive list of common PLSQL extensions

**Comment by zabel-xyz** [comment]
I'll see to complete this list...

**Comment by zabel-xyz** [comment]
Fix in version 1.7.0
