### ISSUE TITLE
Add missing keyword highlighting

### ISSUE THREAD

**Issue by zhudock** [zabel-xyz/plsql-language#34]
**BULK COLLECT**
For _support.function.builtin.advanced.oracle_ suggest replace
`collect` 
with 
`(bulk\s+)?collect`

**treat IS NULL and IS NOT NULL as constants**
For _constant.language.oracle_ suggest replace
`true|false|null|`
with
`true|false|null|is\s+(not\s+)?null`

**Support UNIQUE**
For _keyword.other.ddl.oracle_ suggest replace
`unique index`
with
`unique(\s+index)?`

**Support STORAGE options**
For _keyword.other.ddl.oracle_ suggest add
`storage|tablespace|pct(free|used)|(init|max)trans|logging`

**CURRENT USER**
For _support.function.builtin.advanced.oracle_ suggest replace
`user`
with
`(current\s+)?user`

**Comment by zhudock** [comment]
Also suggest replacing any hard-coded single space characters in the regex patterns with `\s+`

e.g
`primary key`
with
`primary\s+key`

**Comment by zabel-xyz** [comment]
Fix in version 1.3.3
