### ISSUE TITLE
Symbol information (ctrl + shift + O ) is no longer working on linux only

### ISSUE THREAD

**Issue by fernandoTorresan** [zabel-xyz/plsql-language#38]
When i try see procedures and functions of my package with command ( ctrl + shift + o ), it's doesn't working anymore, i don't know why, but i suspect of some recent update of your extension.

I am using linux 64x ubuntu/gnome:

- vs code information:

Version 1.22.1
Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
Date 2018-04-06T00:24:49.616Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

And my user settings:

{
    "files.associations": {
        "*.sql": "plsql"
    },
    "[plsql]": {
        "editor.tabSize": 2,
        "files.encoding": "windows1252"
    },
    "workbench.iconTheme": "vscode-icons",
    "files.encoding": "windows1252",
    "gitlens.codeLens.scopes": [
        "document",
        "containers"
    ],
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressResultsExplorerNotice": true,
        "suppressShowKeyBindingsNotice": true
    },
    "diffEditor.ignoreTrimWhitespace": true,
    "gitlens.gitExplorer.files.layout": "tree"
}

My coworkers are using windowns 7 and apparently works fine.

**Comment by zabel-xyz** [comment]
Since version 1.2.0, I have completely refactored the plsql parser, in order to integrate global variables, constants, types ... Now it's the same parser code to navigate and list the symbols.

Sorry that it doesn't work on the Linux system (I can only test on Windows 10)
Maybe someone can debug this extension on Linux and see what goes wrong ?

Have you tried with test [files] (https://github.com/zabel-xyz/plsql-language/blob/master/test/sql/xyz_myPackage.sql)

**Comment by fernandoTorresan** [comment]
Well, I tried solve this problem doing downgrade of vscode, but it's still doesn't work :cry: 

I also tried either do tests with these files (https://github.com/zabel-xyz/plsql-language/blob/master/test/sql/xyz_myPackage.sql) as you mentioned too, but without success

If someone else is using linux and see this same problem, please comment here, for us to know.

**Comment by eliziersr** [comment]
I have the same problem. My system is Linux. I put a comment in rating page.

**Comment by zabel-xyz** [comment]
I have installed a virtual machine with linux to find out what is going wrong...

**Comment by zabel-xyz** [comment]
I found an issue with case. I have done a commit in github and will publish it soon...

**Comment by fernandoTorresan** [comment]
@zabel-xyz  Thank you very much!!!! 😃

**Comment by zabel-xyz** [comment]
Fixed in version 1.2.3
