### ISSUE TITLE
colourized word list suggestion

### ISSUE THREAD

**Issue by thiagonogueira** [zabel-xyz/plsql-language#4]
First of all congrats and thank you for the great work!

Here are some words don't appear colourized on my sql files I believe it should be:

DROP
FUNCTION
PROCEDURE
NUMBER
CURSOR
COMMIT
EXECUTE
IMMEDIATE
RANK
OVER
PARTITION
BY
COUNT
SUM
EXISTS
PIVOT
UNPIVOT
NOTFOUND

I've taken a look at the source code but since I'm neither a regex nor a sql expert I could easily mess everything up if trying to implement by myself.

Kind Regards,
Thiago

**Comment by zabel-xyz** [comment]
Thank you for the list (some words are already colourized)
![image](https://cloud.githubusercontent.com/assets/16486407/23725171/cea9afb4-044f-11e7-930e-4a9a62c75f3e.png)

I'll complete the keyword list to improve syntax highlight (with your list and another)....

**Comment by thiagonogueira** [comment]
Not sure why, but some words you've posted are not working here... 

![image](https://cloud.githubusercontent.com/assets/755318/23902169/f10007f4-089e-11e7-9ad0-918676acff2a.png)

![image](https://cloud.githubusercontent.com/assets/755318/23902227/2cc6ec76-089f-11e7-8a6c-03f70274f782.png)

![image](https://cloud.githubusercontent.com/assets/755318/23902298/6a2941f4-089f-11e7-8894-f7a562b7a6e1.png)

**Comment by zabel-xyz** [comment]
_procedure_ and _function_ are special keywords.
Currently they are colored only when they appear at the beginning of the line (not after drop or create ...) and with a name after. 

For other keywords:
Which theme do you use? Do they work with another color theme (e.g. Monokai)?
![image](https://cloud.githubusercontent.com/assets/16486407/23922236/d659d0ac-0901-11e7-8408-cb4bf3d43260.png)

**Comment by thiagonogueira** [comment]
I use Agila theme. I've tested colouring schema with Monokai and it worked.

**Comment by zabel-xyz** [comment]
fix in version 0.0.9
