### ISSUE TITLE
bug completion with workspace + plsql.completion.json

### ISSUE THREAD

**Issue by Danieleeee** [zabel-xyz/plsql-language#44]
Hi @zabel-xyz ,
as I mentioned in a previous issue [#32](https://github.com/zabel-xyz/plsql-language/issues/32#issuecomment-390597520) there is a problem in the cohabitation between the completion of the methods of a package in workspace and the completion set with the file plsql.completion.json.
The result is infinite hung.
If you can not solve the problem by code, can you give us the possibility to disable the completion from files in the workspace?

Thanks

**Comment by zabel-xyz** [comment]
Improve this In version 1.3.3. (without settings for now)
