### ISSUE TITLE
Go to definition for tables and views

### ISSUE THREAD

**Issue by ballodia** [zabel-xyz/plsql-language#54]
Hi, @zabel-xyz 

I think it would be useful if "go to definition..." feature could work with tables and views

**Comment by zabel-xyz** [comment]
Yes, useful, but it can not be accomplished with a simple regexparser. I need something more complete like [antlr4](https://github.com/antlr/grammars-v4/blob/master/plsql/PlSqlParser.g4). 
So much more complex and unplanned for a near future

**Comment by mickeypearce** [comment]
What about adding "table", "view" to "PLSQLSymbolKind" ("getSymbolKind") and "regSymbols"? 
It works for "Go To Definiton" and "Peek ..". 
It will make a difference for me. Would that be possible?

**Comment by zabel-xyz** [comment]
Ok, what you want is to consider `Create table or view` (or trigger...)
but filename must contain view or table name in order to work with Go To Definition (Is this limitation acceptable ?).

And some others small adaptations will be necessary, because navigation was thought for packages...

**Comment by mickeypearce** [comment]
Yes, similar to function or procedure... That is very acceptable for me.

**Comment by zabel-xyz** [comment]
Ok, I'll implement something like this...

**Comment by zabel-xyz** [comment]
Published in version 1.6.2
