### ISSUE TITLE
Word "pragma" cause to stop parsing file

### ISSUE THREAD

**Issue by Gepar** [zabel-xyz/plsql-language#59]
After "pragma" word the package header / package body won't be parsed.
Example:
```
create or replace package body is_there_anybody_out_there as
  bulk_error exception;
  pragma exception_init(bulk_error, -24381);

  procedure hidden is begin null; end; -- won't be visible in outline / go to
end;
```
N.B: in previous version word "pragma" was also unsupported but parser seems just ignore it.

**Comment by zabel-xyz** [comment]
Fix in version 1.6.3
I added some tests, see [xyz_myPackage.sql](https://github.com/zabel-xyz/plsql-language/blob/master/main/test/sql/xyz_myPackage.sql)
