### ISSUE TITLE
Breadcrumbs broken - empty bar

### ISSUE THREAD

**Issue by mickeypearce** [zabel-xyz/plsql-language#60]
I think the breadcrumbs are broken in the latest version - no content displayed in the bar.

**Comment by zabel-xyz** [comment]
It works fine for me. It's the same as outline.
![image](https://user-images.githubusercontent.com/16486407/48726325-4761a600-ec2f-11e8-8049-4018cb8ba9f7.png)

**Comment by mickeypearce** [comment]
Sori, looks like it is not a PL/SQL langage problem as it doesn't work in my other projects as well.
