### ISSUE TITLE
Go to Symbol with name in quotes

### ISSUE THREAD

**Issue by khatibMarwan** [zabel-xyz/plsql-language#62]
Hi,
I've just added the extension and it works fine, but when tested Go to definition or go to symbol, it doesn't recognize procedure or function name if surrounded by double quotations.

I am using ODP.NET on Visual Studio which generates script files with qualified object names, e.g., PROCEDURE "HELLO".

Is there any configuration to support that? or current version (1.6.5) doesn't support it?

Thanks

**Comment by zabel-xyz** [comment]
Give me an example of what exactly doesn't work, in order to fix regExpParser.

**Comment by khatibMarwan** [comment]
[sample.zip](https://github.com/zabel-xyz/plsql-language/files/2637250/sample.zip)

Attached sample file contains a procedure "VALIDATE_DATES".
FUNCTION "APPOINTMENT_BYCATEGORY" invokes VALIDATE_DATES(R1, R2, ISTIME, NR1, NR2); at line 60.

Now, if you peek definition for VALIDATE_DATES you will get no definition found message.

Try rename PROCEDURE "VALIDATE_DATES" to PROCEDURE VALIDATE_DATES (_just delete double quotations_), then peek definition works.

**Comment by zabel-xyz** [comment]
Thanks for the sample. This is currently not supported by regExpParser neither by .tmLanguage (colorization failed too)
I'll fix to support this feature.

**Comment by zabel-xyz** [comment]
Fix in version 1.7.0
