### ISSUE TITLE
Symbol is mapped to incorrect root when function is a java stored procedure

### ISSUE THREAD

**Issue by ddangcsu** [zabel-xyz/plsql-language#69]
First of all, thank you for a great extension.

I run into this odd issue where the symbol's parent is incorrectly mapped when declare  a java stored procedure is the package body.  In the example, I was expected to see all the functions/procedure to be sibling of each other with the root symbol mapped to package body ABC.  Instead all the functions/procedure declared after the top level java stored procedure call specification become child/children of that java call specification.

![image](https://user-images.githubusercontent.com/17011759/51621307-192b6b80-1ee9-11e9-8640-ac92641bdb88.png)

The symbol list also show that the as well.
![image](https://user-images.githubusercontent.com/17011759/51621721-f9487780-1ee9-11e9-83c3-18fc2d020c67.png)

**Comment by zabel-xyz** [comment]
Fix in version 1.8.0
