### ISSUE TITLE
Syntax highlighting: Keywords in, as, is are too greedy

### ISSUE THREAD

**Issue by mortenbra** [zabel-xyz/plsql-language#7]
As the image below shows, certain keywords (in, as, is) are too "greedy" and cause wrong highlighting of other keywords and identifiers.

Also, the "set" keyword is differently colored than the rest of the keywords.

![image](https://cloud.githubusercontent.com/assets/9341579/24084707/9d6035ce-0cef-11e7-977b-16bc75fc4fb5.png)

Using the "Blackboard" theme, but the same problem applies regardless of theme.

**Comment by zabel-xyz** [comment]
Oops, fix in version 0.0.10

**Comment by athuth** [comment]
Don't know if this is worth opening a separate issue, but seems like `user` is affected similarly:

![image](https://cloud.githubusercontent.com/assets/13156336/24727528/2bf2c2e8-1a0b-11e7-9e18-3b5083e1e8dd.png)

**Comment by zabel-xyz** [comment]
fix in version 0.0.14
