### ISSUE TITLE
Double quote in single quotes '"' break Goto Symbol list

### ISSUE THREAD

**Issue by zalextus** [zabel-xyz/plsql-language#70]
After this line (double quote in singles quotes) next procedures are not recognized:
l := '"';
For correct recognition need to replace:
Need to replace to:
l := chr(34);

![screen](https://user-images.githubusercontent.com/24762346/53176507-41e57480-35ff-11e9-9214-b04e644d7223.png)

**Comment by zabel-xyz** [comment]
Fix in version 1.8.0
