### ISSUE TITLE
Navigation does not work with regexp

### ISSUE THREAD

**Issue by StefanRoess** [zabel-xyz/plsql-language#74]
I use the current version (1.7) of xyz on a windows host. 
I have opened, for example  *.pkb PL/SQL File.
The navitagion via CTRL+P and ALT-GR+@ does not show all procs and funcs.
The reason is the **regexp_*** function, which is inside of another function.
In my case, i use regexp_count..., but also any other regexp_* function caused in a break for showing all funcs/procs in the navigation window.

Any reason why?

**Comment by zabel-xyz** [comment]
Can you give me an example ? In order to reproduce your issue.
(The latest version is 1.8.1)

**Comment by StefanRoess** [comment]
![image](https://user-images.githubusercontent.com/15950028/57538037-d1b9d580-7347-11e9-8da2-91f316a86157.png)

The newest version seems to be 1.7, look at the picture, there is the german word "Aktuell" means current.

![image](https://user-images.githubusercontent.com/15950028/57537486-abe00100-7346-11e9-8d0f-030058ba3b3e.png)

And here is an example. You can see only three procs/funcs. But in reality i have much more in my package.
![image](https://user-images.githubusercontent.com/15950028/57537786-493b3500-7347-11e9-98da-07f7fd5749cc.png)

The reason is the regexp_count function: 
![image](https://user-images.githubusercontent.com/15950028/57537879-7982d380-7347-11e9-8439-9abc50be05c0.png)

all the following funcs/procs will not displayed in the overview listing:
![image](https://user-images.githubusercontent.com/15950028/57538131-088feb80-7348-11e9-9693-fe7d7ea9670b.png)
Only the first three proc/func.  With the appearance of the first regexp_* function inside a proc/func all the following won't appear.

Do you have any idea?
As soon as i removed all kind of regexp_* all funcs and procs will be displayed.
Strange behaviour.

**Comment by zabel-xyz** [comment]
Thanks for the example,
The last published version is [1.8.1](https://marketplace.visualstudio.com/items?itemName=xyz.plsql-language) => update your vscode version.

You find a bug, 
The problem here is not `regexp_` but variable `pi_case`, As soon as I rename it to `pi_cse`, all funtions will be displayed. I guess there is a confusion in regExParser with keyword `case`. 

I'll fix it...

**Comment by zabel-xyz** [comment]
Fix in version 1.8.2

**Comment by StefanRoess** [comment]
Thank you for fixing the regexp issue. Right now, after all updates and your fixing it works.
