### ISSUE TITLE
Mouse over - problem with the selection, stopping on dots

### ISSUE THREAD

**Issue by zerabba** [zabel-xyz/plsql-language#85]
I've made an extension to remote debug in PL/SQL with DBMS_JDWP and when I use it with your extension, I have a problem with the mouse over to evaluate the value. I tried with the other extension (oracle dev tools) and the evaluation is working.

Maybe, it's easier to explain with a sample: 

![image](https://user-images.githubusercontent.com/1078026/77905741-1794ca80-7287-11ea-8c26-601610f88150.png)

If I put the mouse on USE_NAME, it will select not only USE_NAME (it's the case in your extension), but the whole expression (LTPLTST.USE_NAME).

Would it be possible to change the behaviour to return the whole expression? It would be easier for me to evaluate the value.

**Comment by zabel-xyz** [comment]
Hello, 
You made a great extension!

To define what a word is in the context of debugging, you need to adapt your code.
vscode.TextDocument.getWordRangeAtPosition() has a second parameter, it is a regular expression that describes what a word is.

For example, you can use my regular expression without dot character

```
	// override VS Code's default implementation of the debug hover
	vscode.languages.registerEvaluatableExpressionProvider('plsql', {
		provideEvaluatableExpression(document: vscode.TextDocument, position: vscode.Position): vscode.ProviderResult<vscode.EvaluatableExpression> {
			// const plsql_wordPattern: /(-?\d*\.\d\w*)|([^\`\~\!\@\%\^\&\*\(\)\-\=\+\[\{\]\}\|\;\:\'\"\,\.\<\>\/\?\s]+)/;
			const wordPattern = /(-?\d*\.\d\w*)|([^\`\~\!\@\%\^\&\*\(\)\-\=\+\[\{\]\}\|\;\:\'\"\,\<\>\/\?\s]+)/;
			const wordRange = document.getWordRangeAtPosition(position, wordPattern);
			return wordRange ? new vscode.EvaluatableExpression(wordRange) : undefined;
		}
	});
```

**Comment by zerabba** [comment]
Thanks for your reply. I will change that way.
